gst-plugins-base: fix compilation error for the git version of the recipe
Fixes:

fatal error: xdg-shell-client-protocol.h: No such file or directory

caused by wayland scanner generated the header files outside the src directory.

Signed-off-by: Andrey Konovalov <andrey.konovalov@linaro.org>